# Generated by Django 3.2.2 on 2023-11-05 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20231018_1728'),
        ('accounts', '0003_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facultad',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='social.facultad'),
        ),
    ]
