# Generated by Django 3.2.2 on 2023-10-18 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcomments',
            name='comment',
            field=models.TextField(default='valor de comentario'),
        ),
        migrations.AddField(
            model_name='socialcomments',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.socialpost'),
        ),
    ]
